refactor: use importlib instead of pkg_resources
Becksteinlab/GromacsWrapper pull request #273
Opened 2023-11-13 09:23 UTC by jandom

Removing the setuptools dep, use importlib instead

2023-11-14 16:50 UTC, jandom commented
Not using importlib at all – and i'm not sure this will work outside of CI/CD?

2023-11-15 06:10 UTC, orbeckst requested changes
Probably needs a more sophisticated version, see comment.

2023-11-15 06:10 UTC, orbeckst commented on gromacs/config.py
> +    resource_path = Path(__package__) / dirname
This does not necessarily work with installed packages, I think, or at least if these are zipped or eggs or whatever.

https://importlib-resources.readthedocs.io/en/latest/using.html#file-system-or-zip-file and in particular the `atexit` solution in https://importlib-resources.readthedocs.io/en/latest/migration.html#pkg-resources-resource-filename

Probably needs something like
```python
import importlib.resources as importlib_resources
from contextlib import ExitStack
import atexit

file_manager = ExitStack()
atexit.register(file_manager.close)
resource_path = importlib_resources.files(gromacs.config) / dirname
path = file_manager.enter_context(importlib_resources.as_file(resource_path))
```

2023-11-25 21:05 UTC, jandom commented
This just looks hard and I'm not enjoying it too much – let's work on sth else, and return to this one with a fresh mind later

2023-11-25 21:05 UTC, closed without merging

2023-11-27 17:10 UTC, orbeckst commented
That’s fair ;-)